export interface IncomingMoneyDetailsDto {
  incomingMoneyId:number;
  futureMoneyId:number;
  userId:number;
  typeOfOperation:string;
  customerCode:string;
  customerNameSurname:string;
  promissoryNumber:string;
  transactionAmount:number;
  amountPaid:number;
  futureAmount:number;
  futureMoneyRegistrationDate:Date;
  incomingMoneyRegistrationDate:Date;
  incomingAmount:number;
  inComingMoneyDescription:string;
  futureMoneyDescription:string;
  futureMoneyStatus:boolean;
  incomingMoneyStatus:true;
}
